In [20]:
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import Rectangle
from numpy import genfromtxt
import numpy as np


In [36]:
aorlist = genfromtxt('/home/kecai/w49/aorlist.csv', delimiter=',')
coverage_list_t = np.transpose(aorlist)[5:9]
coverage_list = np.transpose(coverage_list_t)
print coverage_list

[[ 286.3697496   286.7857496     7.37732703    9.09466036]
 [ 287.3697339   287.7217339     9.04551151    9.28817818]
 [ 287.56391937  287.98258603    8.03584082   10.76917415]
 [ 287.38586037  287.80452703    7.70051032   10.43117699]
 [ 287.74087423  288.16220757    8.37201772   11.10535105]
 [ 287.20859177  287.62725843    7.36518359   10.09585026]
 [ 287.03076477  287.44943143    7.0267972     9.75746386]
 [ 287.92099337  288.33966003    8.70965034   11.440317  ]
 [ 288.09876743  288.52010077    9.04598599   11.77665265]
 [ 287.66511003  287.93444337    9.04604635    9.39271302]
 [ 287.6621043   287.9101043     8.9858961     9.23922943]
 [ 286.4312639   286.7672639     9.02770928   11.25704262]
 [ 285.4615123   285.7975123     7.17541616    9.40474949]
 [ 285.58006153  285.92139487    7.40719243    9.63652576]
 [ 285.703558    286.039558      7.63876852    9.86810185]
 [ 285.8250379   286.1610379     7.87021007   10.0995434 ]
 [ 286.18531513  286.52664847    8.56276723   10.7947672

In [35]:
coverage_map = plt.figure()
ax = coverage_map.add_subplot(111)
ra_min = min(coverage_list_t[0])
ra_max = max(coverage_list_t[1])
dec_min = min(coverage_list_t[2])
dec_max = max(coverage_list_t[3])

padding = 0.01

ax.set_xlim([ra_min-padding,ra_max+padding])
ax.set_ylim([dec_min-padding,dec_max+padding])

print ra_min, ra_max, dec_min, dec_max

285.4615123 288.520100767 7.0267971965 11.7766526535


In [38]:
for i in coverage_list:
    ax.add_patch(
        Rectangle(
            (i[0], i[2]), i[1]-i[0], i[3]-i[2], fill=False
        )
    )
coverage_map.savefig('/home/kecai/w49/coverage_map.png', dpi=900, bbox_inches='tight')